apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    chart: {{ .Chart.Name | lower }}
    release: {{ .Release.Name | lower }}
    {{- if eq .Values.environment "prod" }}
    environment: "production"
    {{- else if eq .Values.environment "dev" }}
    environment: "development"
    {{- else }}
    environment: "qa"
    {{- end }}
  name: {{ .Release.Name | lower | quote }}
spec:
  replicas: {{ .Values.replicaCount | int }}
  selector:
    matchLabels:
      chart: {{ .Chart.Name | lower }}
      release: {{ .Release.Name | lower }}
  strategy: {}
  template:
    metadata:
      labels:
        chart: {{ .Chart.Name | lower }}
        release: {{ .Release.Name | lower }}
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
        ports:
          {{- range .Values.ports }}
          - name: {{ .name }}
            containerPort: {{ .port | int }}
          {{- end }}
        {{- if (.Values.enableLogging ) }}
      - name: fluentd
        image: fluent/fluentd
        {{- end }}
status: {}
