nameOverride: ""
replicaCount: 1
enableLogging: True
image:
  repository: "nginx"
  tag: "1.27"
ports:
  - name: http
    port: 80
  - name: https
    port: 443
  - name: metrics
    port: 9090
environment: dev

mysql:
  enabled: true
  auth:
    database: "my_custom_db"
    username: "customowner"
    password: "test12345"
  primary:
    service:
      type: NodePort

redis:
  enabled: true
